name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: '@fastry'
          
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install
      - run: yarn compile

      - name: Auth to npm Github Registry
        run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NODE_AUTH_TOKEN }};

      - name: Push packages to NPM Registry
        run: yarn lerna publish from-package -y --no-verify-access

#      - name: Set config pointing to Github Registry
#        run: npm config set @knack-ux:registry https://npm.pkg.github.com;
#
#      - name: Auth to npm Github Registry
#        run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }};
#
#      - name: Push packages to Github NPM Registry
#        run: yarn lerna publish from-package -y --no-verify-access
